project:
  type: website

website:
  site-url: https://tobhu1981.github.io/quartTest/
  title: "TBA - Verstehen und Anwenden"
  description: "Dokumentation der IQB-Webanwendungen zum computerbasierten Testen - TBA"
  favicon: assets/favicon.ico
  back-to-top-navigation: true
  page-navigation: true
  repo-url: https://github.com/tobhu1981/quartTest
  repo-actions: []
  navbar:
    pinned: true
    search: true
    logo: assets/IQB-klein.png
    background: '#536171'
  page-footer:
    border: true
    background: light
    right:
      - text: "IQB 2025"
        href: https://www.iqb.hu-berlin.de
      - icon: rss
        href: news/index.xml
    left:
      - text: "{{< fa house >}}"
        href: index.qmd
      - icon: github
        href: https://github.com/iqb-berlin/tba-info
        aria-label: Source Code
  sidebar:
    style: "floating"
    lang: de
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Start
      - section: Einführung
        href: intro/index.qmd
        contents:
          - href: intro/bt.qmd
            text: Bildungstrend
          - href: intro/vera.qmd
            text: VERA
          - section: Installation
            href: intro/install/index.qmd
            contents:
            - href: intro/install/studio-super-admin/index.qmd
              text: "Studio: Super-Admin"
            - href: intro/install/configuration.qmd
              text: "TC: Konfiguration"
            - href: intro/install/load-test.qmd
              text: "Lasttests"
            - href: intro/install/security.qmd
              text: "Datensicherheit"
            - href: intro/install/offline.qmd
              text: "Offline-Szenario"
            - href: intro/install/e2e.qmd
              text: "Software-Tests"
            - href: intro/install/releases.qmd
              text: "Release-Plan"

      - section: "Aufgaben entwickeln"
        href: tasks/index.qmd
        contents:
          - section: "Organisieren"
            href: tasks/manage/index.qmd
            contents:
              - href: tasks/manage/roles.qmd
                text: "Rollen und Rechte"
              - href: tasks/manage/workspaces.qmd
                text: Arbeitsbereiche
              - href: tasks/manage/move-and-copy.qmd
                text: Verschieben und Kopieren
              - href: tasks/manage/task-sequence.qmd
                text: Aufgabenfolgen
              - href: tasks/manage/verona-modules.qmd
                text: Verona-Module
              - href: tasks/manage/metadata.qmd
                text: Metadaten

          - section: "Aufgaben gestalten"
            href: tasks/design/index.qmd
            contents:
              - section: "Standardmodus"
                href: tasks/design/basic/index.qmd
                contents:
                  - tasks/design/basic/Allgemeine_Anleitung/index.qmd
                  - tasks/design/basic/Text_ST_Assistent/index.qmd
                  - tasks/design/basic/Audio_ST_Assistent/index.qmd
                  - tasks/design/basic/MC_Text_Assistent/index.qmd
                  - tasks/design/basic/MC_Bild_Assistent/index.qmd
                  - tasks/design/basic/CMC-Assistent/index.qmd
                  - tasks/design/basic/Antwortfelder_Assistent/index.qmd
                  - section: "Drag & Drop"
                    contents:
                    - tasks/design/basic/DaD/DaD_Assistent_ZO_Einseitig_Elemente_uber_Ziel/index.qmd
                    - tasks/design/basic/DaD/DaD_Assistent_ZO_Einseitig_Elemente_neben_Ziel/index.qmd
                    - tasks/design/basic/DaD/DaD_Assistent_Sortieren/index.qmd
                  - tasks/design/basic/Markieren_Assistent/index.qmd
                  - tasks/design/basic/Rechenkastchen_Assistent/index.qmd
                  - tasks/design/basic/GGB_Assistent/index.qmd
                  - section: "Medienelemente"
                    contents:
                    - tasks/design/basic/Medienelemente/Text/index.qmd
                    - tasks/design/basic/Medienelemente/Bild/index.qmd
                    - tasks/design/basic/Medienelemente/Audio/index.qmd
                    - tasks/design/basic/Medienelemente/Video/index.qmd
                  - tasks/design/basic/Lueckentext_Verbundelement/index.qmd
                  - tasks/design/basic/Tabellen_Assistent/index.qmd
                  - tasks/design/basic/Glossar/index.qmd
              - section: "Erweiterter Modus"
                href: tasks/design/extended/index.qmd
                contents:
                  - tasks/design/extended/Elementeinstellungen/index.qmd
                  - tasks/design/extended/Abschnittseinstellungen/index.qmd
                  - tasks/design/extended/Elemente/index.qmd
                  - section: "Hervorhebungen & Sichtbarkeiten"
                    href: tasks/design/extended/Hervorhebungen_Sichtbarkeiten/index.qmd
                    contents:
                      - tasks/design/extended/Hervorhebungen_Sichtbarkeiten/Buttonverlinkung.qmd
                      - tasks/design/extended/Hervorhebungen_Sichtbarkeiten/Hervorhebungen.qmd
                      - tasks/design/extended/Hervorhebungen_Sichtbarkeiten/Markieren.qmd
                      - tasks/design/extended/Hervorhebungen_Sichtbarkeiten/Sichtbarkeitskaskaden.qmd
              - section: "GeoGebra"
                href: tasks/design/geogebra/index.qmd
                contents:
                  - href: tasks/design/geogebra/intro/index.qmd
                    text: "Einführung"
                  - tasks/design/geogebra/BalkenSaulen/index.qmd
                  - tasks/design/geogebra/Tortendiagramm/index.qmd
                  - tasks/design/geogebra/Messen/index.qmd
                  - tasks/design/geogebra/Geobrett/index.qmd
                  - tasks/design/geogebra/Koordinatensystem/index.qmd
                  - tasks/design/geogebra/Zahlenstrahl/index.qmd
              - section: "Bild/Audio/Video"
                href: tasks/design/media/index.qmd
                contents:
                  - href: tasks/design/media/Audio_Parameter.qmd
                    text: "Audio-Parameter"
                  - href: tasks/design/media/Video_Parameter.qmd
                    text: "Video-Parameter"
                  - href: tasks/design/media/Audios_konvertieren.qmd
                    text: "Audio bearbeiten"
                  - href: tasks/design/media/Bilder_vorbereiten.qmd
                    text: "Hinweise zu Bildern"
                  - href: tasks/design/media/Bilder_einfarben/index.qmd
                    text: "Bilder einfärben"
                  - href: tasks/design/media/Bilder_skalieren/index.qmd
                    text: "Bilder Größe ändern"
              - section: "Einfache Formulare"
                href: tasks/design/simple-forms/index.qmd
                contents:
                    - section: "ABI-Player"
                      href: tasks/design/simple-forms/Abi_Player/index.qmd
                      contents:
                        - tasks/design/simple-forms/Abi_Player/Syntax_im_Detail.qmd
                        - tasks/design/simple-forms/Abi_Player/Antwortdaten.qmd
                        - tasks/design/simple-forms/Abi_Player/Praktische_Hinweise.qmd
              - href: tasks/design/speedtest/index.qmd
                text: Speedtest
          - section: "Kodierschema"
            href: tasks/coding-scheme/index.qmd
            contents:
              - tasks/coding-scheme/steps.qmd
              - href: tasks/coding-scheme/basic.qmd
                text: Basisfälle
              - href: tasks/coding-scheme/extended.qmd
                text: Sonderfälle

      - section: Studie durchführen
        href: Testcenter/index.qmd
        contents:
          - Testcenter/Workspace/index.qmd
          - Testcenter/Zugriffsrechte/index.qmd
          - section: Testinhalte
            href: Testcenter/Testinhalte/index.qmd
            contents:
            - Testcenter/Testinhalte/erstellung-inhalte.qmd
            - Testcenter/Testinhalte/unit-xml.qmd
            - Testcenter/Testinhalte/booklet-xml.qmd
            - Testcenter/Testinhalte/testtaker-xml.qmd
          - Testcenter/Datenauswertung/index.qmd
          - Testcenter/System_Check/index.qmd
          - Testcenter/Gruppenmonitor/index.qmd
          - Testcenter/Adaptives_Testen/index.qmd
          - section: "Schritt für Schritt"
            href: Testcenter/Studie_durchfuehren/index.qmd
            contents:
              - Testcenter/Studie_durchfuehren/Anforderungen.qmd
              - Testcenter/Studie_durchfuehren/Studienkonfiguration.qmd
              - Testcenter/Studie_durchfuehren/Durchfuehrung.qmd
              - section: "Beispielstudie"
                href: Testcenter/Studie_durchfuehren/Beispielstudie/index.qmd
                contents: 
                  - Testcenter/Studie_durchfuehren/Beispielstudie/Schritt1.qmd
                  - Testcenter/Studie_durchfuehren/Beispielstudie/Schritt2.qmd
                  - Testcenter/Studie_durchfuehren/Beispielstudie/Schritt3.qmd
          - href: Testcenter/faq/index.qmd
            text: FAQ

      - section: "Kodieren und Auswerten"
        href: coding/index.qmd
        contents:
            - section: "Datenstrukturen"
              href: coding/data-structures/index.qmd
              contents:
                - href: coding/data-structures/response.qmd
                  text: Antwort
                - href: coding/data-structures/coding-scheme.qmd
                  text: Kodierschema
            - coding/response-status.qmd
            - coding/missings.qmd
      - href: Schulungsmaterial/index.qmd
        text: "Schulungsmaterial"
      - href: news/index.qmd
        text: "Aktuell"
format:
  html:
    theme: 
      - zephir
      - custom.scss
    css: styles.css
    toc: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    code-overflow: scroll
    code-copy: true
    code-block-background: true
    highlight-style: ayu-dark
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
