project:
  type: website

website:
  site-url: https://tobhu1981.github.io/quartTest/
  title: "TBA - Verstehen und Anwenden"
  description: "Dokumentation der IQB-Webanwendungen zum computerbasierten Testen - TBA"
  favicon: assets/favicon.ico
  back-to-top-navigation: true
  page-navigation: true
  repo-url: https://github.com/tobhu1981/quartTest
  repo-actions: []
  navbar:
    pinned: true
    search: true
    logo: assets/IQB-klein.png
    background: '#536171'
  page-footer:
    border: true
    background: light
    right:
      - text: "IQB 2025"
        href: https://www.iqb.hu-berlin.de
      - icon: rss
        href: news/index.xml
    left:
      - text: "{{< fa house >}}"
        href: index.qmd
      - icon: github
        href: https://github.com/iqb-berlin/tba-info
        aria-label: Source Code
  sidebar:
    style: "floating"
    lang: de
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Start
      - section: Einführung
        href: intro/index.qmd
format:
  html:
    theme: 
      - zephir
      - custom.scss
    css: styles.css
    toc: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    code-overflow: scroll
    code-copy: true
    code-block-background: true
    highlight-style: ayu-dark
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
