---
lang: de
title: "GeoGebra"
---

GeoGebra ist eine vielseitige Anwendung, die es uns erlaubt Aufgaben zu konstruieren, die über übliche Formularfunktionalität weit hinausgehen. Schüler*innen können zeichnen, mit Diagrammen interagieren und Figuren verschieben. Sogar Aufgaben in 3D sind denkbar. Für weitere Informationen speziell auch zur sehr freien Nutzungslizenz siehe die [Website von GeoGebra](https://www.geogebra.org).

Im Folgenden wird auf die wichtigsten Features von GeoGebra zur Entwicklung von Aufgaben für das IQB Studio eingegangen. Dazu gibt es ein Beispiel einer Aufgabe, die wir von Null entwickeln. Es gibt allerdings auch Vorlagen für häufig vorkommende Aufgabentypen (s. u.).

Falls Sie noch nie mit GeoGebra gearbeitet haben empfehlen wir, unsere [Einführung](intro/index.qmd) zuerst zu lesen und das Beispiel Schritt für Schritt mitzugehen. Danach können Sie sich an jede Art von Aufgabe wagen. Sollten Sie einmal nicht weiterkommen hilft Ihnen diese Anleitung, das offizielle [GeoGebra Wiki](https://wiki.geogebra.org/de/Men%C3%BCleiste) oder die Suchmaschine Ihrer Wahl.

In IQB-Aufgaben sind vor allem die folgenden Funktionen genutzt:

* [Balken- und Säulendiagramm](BalkenSaulen/index.qmd)
* [Tortendiagramme zum Einfärben](Tortendiagramm/index.qmd)
* [Messen](Messen/index.qmd)
* [Geobrett](Geobrett/index.qmd)
* [Koordinatensystem](Koordinatensystem/index.qmd)
* [Zahlenstrahl](Zahlenstrahl/index.qmd)

Für die Anleitungen sind teilweise Vorlagen des IQB verfügbar:

{{< downloadthis IQB_GeoGebra_Templates.zip label="Herunterladen GeoGebra-Vorlagen" dname="IQB_GeoGebra_Templates" icon=file-zip >}}