---
lang: de
title: "Eine Studie durchführen mit dem IQB-Testcenter"
---

Dieser Abschnitt erläutert die Funktionen der Webanwendung IQB-Testcenter und richtet sich an Verantwortliche, die mit der Vorbereitung und Durchführung beauftragt sind. Der Begriff **Studie** steht hierbei gleichermaßen für Leistungstests und für Befragungen. Als Voraussetzung muss das IQB-Testcenter muss auf einem Server installiert sein, und ein Super-Admin-Account muss zur Verfügung stehen.

* Die Konzentration auf die Funktion "Durchführung" ist wichtig, da die Tests und Befragungen des IQB und der Länder sehr große Zahlen an Testpersonen bewältigen müssen. Die Entwicklung der Testinhalte übernimmt eine andere Software [IQB-Studio](../tasks/index.qmd), und auch die Kodierung und Datenanalyse sind separat gelöst.
* Die Einstellungen, die die Durchführung eines Tests oder einer Befragung steuern, sollen in Dateiform vorliegen. Das IQB-Testcenter verfügt nicht über visuelle Konfigurationsdialoge und aufwändige Assistenten, um z. B. Zeitbegrenzungen für Aufgabenblöcke zu definieren. Statt dessen werden XML-Dateien eines speziellen, ausführlich dokumentierten Formats in das IQB-Testcenter hochgeladen. Nur über diesen Weg ist es möglich, die Parameter eines Tests festzulegen.
* Eine Integration in verschiedene Architekturen muss einfach möglich sein. Die Länder betreiben mitunter Portale für Lehrkräfte, in denen die Personenverwaltung bereits vorhanden ist. Auch Rückmeldung der Ergebnisse soll oft über vorhandene Webanwendungen erfolgen. Daher ist das IQB-Testcenter gut über eine Schnittstelle (API) mit Daten zu speisen, und über das API können gut die Antworten und Logdaten heruntergeladen werden. Die Interaktion von Web-Software auf anderen Servern mit dem IQB-Testcenter ist optimiert.

**Ausgewählte Funktionen**

* Anmeldung der Testperson: Über Link (z. B. QR-Code), Name und Kennwort oder zweistufig mit einem zusätzlichen Code
* Anmeldung ohne Personenbezug, z. B. für Befragungen
* Anmeldung im Demo- oder Review-Modus, ohne die Antworten zu speichern
* Mehrere Testhefte: Eine Testperson kann mehrere Testhefte nacheinander bearbeiten mit denselben Anmeldedaten
* zeitliche Beschränkung von Testteilen: Für eine bestimmte Anzahl Aufgaben steht der Testperson eine begrenzte Zeit zur Verfügung
* Fortsetzung erst mit Freigabewort: Die Testdurchführung z. B. in einer Klasse kann synchronisiert werden, indem die Testleitung ein Wort ansagt, mit dem dann der Test fortgesetzt werden kann
* Fortsetzung erst nach vollständiger Präsentation: Um zu vermeiden, dass Teile einer Aufgabe übersehen werden, kann das Weiterblättern solange unterbunden werden, bis alle Audio-Sequenzen abgespielt wurden und alle Seiten vollständig angezeigt wurden
* Fortsetzung erst nach vollständiger Beantwortung
* sofortige Speicherung: Alle Antworten werden sofort zum Server gesendet; nach Abbruch der Testung oder Absturz eines Computers bzw. Browsers kann der vorherige Stand wiederhergestellt werden
* In Abhängigkeit gegebener Antworten und einer zuvor festgelegten Wichtung, kann zu bestimmten Aufgaben verzweigt werden (adaptives Testen)

Lesen Sie weiter:

* Die Steuerung eines Tests ist im Abschnitt [Testinhalte](Testinhalte/index.qmd) ausführlich beschrieben.
* Im Abschnitt [Datenauswertung](Datenauswertung/index.qmd) finden Sie Verfahren und Spezifikationen zum Download der Ergebnisse.
* Ein [System-Check](System_Check/index.qmd) kann im Vorfeld der Testung mit dem Serversystem und der Schulhard- und -software durchgeführt werden, um Schwachstellen aufzugedecken und mögliche Probleme bei der Durchführung zu vermeiden.
* Über eine spezielle Anmeldung kann die Testleitung einen [Gruppenmonitor](Gruppenmonitor/index.qmd) aufrufen. Man kann darüber den Fortschritt jeder Testperson einer Gruppe beobachten. Man kann das Weiterleiten in andere Blöcke erzwingen, den Test pausieren, beenden oder sperren.
* Über eine [Schritt-für-Schritt-Anleitung](Studie_durchfuehren/index.qmd) kann man gut den Arbeitszyklus verstehen.
* [Häufige Fragen](faq/index.qmd) werden beantwortet.