---
lang: de
title: "Häufig gestellte Fragen"
---

### Wie können Fehler gemeldet werden?

**An die Hotline**

Die Verantwortlichen einer Studie bzw. die Kolleg:innen der Hotline können oft helfen, wenn sie Informationen über das Problem bekommen. Bei einem Fehlerbericht sollten stets folgende Informationen dabei sein:

* Name und Version des Betriebssystems, z. B. Windows 10
* Name und Version des Browsers, z. B. Firefox 100.0.2 (64-Bit)
* Version des Testcenters (zu finden bei Startbildschirm, dann Impressum/Datenschutz), z. B. Version 12.1.7/12.4.1/4.0.3

Es reicht ein Screenshot mit einem Handy, dann spart man sich viel Text. Ansonsten bitte die Fehlersituation so genau wie möglich beschreiben.

**An das Entwicklerteam**

Über die obigen Daten hinaus kann man noch mehr Informationen schicken, wenn das Problem dem Entwicklerteam vorgelegt werden soll:

* Das Wichtigste beim Berichten von Fehlern ist der Fehlerbericht, der bei jeder Fehlermeldung im Testcenter angezeigt und heruntergeladen werden kann. Im Idealfall
  ist das Testcenter [so konfiguriert](https://iqb-berlin.github.io/tba-info/Testcenter/install/configuration.html),
  dass er auf Knopfdruck automatisch gesendet werden kann.
* Interne Meldungen des Browsers: Man kann (außer bei iPads) bei Browsern ein Fenster öffnen, wo der Browser eventuell weitere Fehlermeldungen hineinschreibt. Die Konsole wird in Firefox, Edge und Chrome mit der Taste F12 geöffnet. In Safari muss zuerst das Entwickler-Menu aktiviert werden. Anschließend kann mit der Tastenkombinationen: **Cmd + Option + C** die Konsole geöffnet werden.
Alternativ kann mit der rechten Maustaste auf die Webseite und dann auf „Element überprüfen“ geklickt werden.
* Protokolle des Servers: Jede Person mit Serverzugriff kann Protokolle herunterladen, die die Fehlersuche noch einmal deutlich vereinfachen können.

### Allgemeine Hinweise zu typischen Problemen

Es sind viele Betriebssysteme in Nutzung, viele Versionen, viele Browser, und man kann durch Einstellungen auf dem System das Verhalten dieser Komponenten und damit des Tests drastisch verändern. Damit gehen manchmal Probleme einher, die durch einige Maßnahmen schnell behoben werden können:

* Ein einfaches Neuladen der Seite hilft manchmal. Eine Testperson muss sich in diesem Fall nicht neu anmelden und landet sofort bei der Aufgabe, die zuletzt bearbeitet wurde. Wenn für die Bearbeitung einer Aufgabenfolge eine Maximalzeit gesetzt wurde, dann wird die vor dem Neuladen verstrichene Zeit abgezogen und man startet also nicht neu.
* Zwischenspeicher (Cache) des Browsers löschen: Manchmal speichert der Browser Teile der Programmierung. Sollte aber auf dem Server eine neue Version dieser Programmierung vorliegen, muss diese unbedingt geladen werden - sonst funktioniert die Kommunikation mit dem Server nicht. Die Vorgehensweise ist [hier](https://www.go4u.de/browser-cache-leeren.htm) beschrieben.
* Browser-Plugins deaktivieren/deinstallieren: Es gibt abenteuerliche Erweiterungen für Browser, die mehr Sicherheit, bessere Performance, weniger Werbung, mehr Privatsphäre usw. versprechen. Oft greifen diese Erweiterungen aber massiv in die Kommunikation des Browsers mit dem Server ein und verfälschen Daten. Bei Problemen sollte man also diese Add-Ons usw. zumindest zeitweise deaktivieren.
* Anderen Browser benutzen: Die Web-Standards werden unterschiedlich durch die Browser implementiert. Daher lohnt es sich bei Problemen, auf einen anderen Browser zu wechseln.

### Wie kann ich auf das Testcenter zugreifen?

Der Zugriff erfolgt mittels Adresseingabe in Ihrem Webbrowser. Beachten Sie bitte: Das Testcenter muss zuvor in Ihrer IT-Netzstruktur auf einem dafür geeignetem Server installiert werden. Die Serveradresse erhalten Sie dann von Ihrem IT-Dienstleister oder den internen Administrator\*innen.

### Welchen Browser sollte ich verwenden?

Es gibt da derzeitig keine Vorgaben seitens des IQB. Empfohlen werden die gängigen Browser, wie Google Chrome oder Firefox. **Mehr Information zu den Anforderungen an die Browser sind [hier](/Testcenter/index.qmd) zu finden.**

### Wie wird das Testcenter installiert?

Mehr Informationen sind zu finden im Kapitel: Testcenter/Installation

### Ist es möglich im Vorfeld die Eignung der Geräte für eine Studiendurchführung zu testen?

Das Testcenter bietet einen sogenannten **System-Check** an. Dieser kann im Vorfeld auf dem Zielsystem ausgeführt werden. Mehr Informationen dazu sind im Kapitel: Testcenter/System-Check zu finden.

### Wie melde ich mich am Testcenter an?

**Anmeldung als Admin:**

Eingabe der Testcenter-Serveradresse in einen Browser. Die Anmeldung erfolgt dann via Benutzernamen und Passwort und dem Schalter: "Weiter als Admin". Die Zugangsdaten werden von entsprechend berechtigten Personen (SuperAdmin) im Testcenter eingerichtet.

**Anmeldung als Testperson:**

Die Anmeldung erfolgt via festgelegter Zugangsdaten in der Testtaker-XML und dem Schalter: "Weiter".

### Warum sehe ich nach der Anmeldung als Administrator keine Inhalte im Testcenter?

Eventuell sind keine Inhalte zu sehen, weil die Administrator\*innen keine Arbeitsbereiche für Sie freigegeben haben. Wenden Sie sich dazu bitte an die Administrator\*innen.

### Wie lade ich Inhalte in meinen Arbeitsbereich?

Öffnen Sie Ihren Bereich, wechseln Sie zum Tab: **Dateien** und klicken Sie auf die kleine Wolke im rechten Bereich des Fensters.

### Warum werden meine Testdateien vom Testcenter abgelehnt?

Hier kann es verschiedene Gründe geben. Vielleicht wurden die Daten in der falschen Reihenfolge geladen oder es fehlen abhängige Dateien. **Mehr dazu ist dem Kapitel: Testcenter/Daten und Prozesse/Daten Upload.**

### Warum werden beim Laden manche Dateien mit einem orangefarbenen Dreieck versehen?

Es gibt hier eventuell mehrere Ursachen:

* Es erscheint ein orangefarbenes Dreieck mit dem Vermerk: File has no link to XSD-Schema.
   * In Ihrer Testdatei ist kein Verweis auf die zugehörige Schema-Definition gesetzt.

* Es erscheint ein orangefarbenes Dreieck mit dem Vermerk: .....never used
   * Ihre Testdatei wird noch von keiner anderen Testdatei aufgerufen bzw. eingebunden.

### Wie bearbeite ich meine Testdateien?

Da es sich bei den Testdateien um XML-Dateien handelt, empfiehlt sich ein Editor der eine Hervorhebung der XML-Syntax ermöglicht. Generell ist aber eine Bearbeitung mit jedem Texteditor möglich.

### Wie werden meine Änderungen an einer der Testdateien wirksam?

Nach Speicherung der Änderungen, muss die geänderte Datei erneut in das Testcenter geladen werden.

### Wie groß ist mein Testheft?

In der Dateiansicht eines Arbeitsbereichs wird die Testheftgröße angezeigt. Um zu verstehen, wie sich diese Größe bildet, müssen die Bestandteile eines Testheftes verstanden werden. Hierfür werden alle Datei unterteilt in:

**Ressourcen:**

Hier werden alle Dateien, die als Ressource für die einzelnen Units benötigt werden, aufgelistet. Ressourcen sind bspw. Player, Pakete (GeoGebra etc.) und Kodierschemen. Die angezeigten Größen in KByte oder Byte entsprechen der tatsächlichen Dateigröße dieser Dateien.

**Units:**

Hier werden die geladenen Units aufgelistet. Die angezeigten Größen neben jeder Unit setzen sich zusammen aus den verwendeten Ressourcen abzgl. des verwendeten Players und der eigentlichen Dateigröße der Unit-XML. Der Player wird an dieser Stelle nicht mit eingerechnet, weil der Player nicht zwingend für die Funktionstüchtigkeit einer Unit erforderlich ist. Er stellt die Unit ja nur dar.

**Testhefte:**

Die angezeigte Größe setzt sich zusammen aus der angezeigten Größe der eingebundenen Units, der Dateigröße der Booklet-XML und dem oder der verwendeten Player. Wichtig zu verstehen ist hierbei, dass der Player immer nur einmal mit eingerechnet wird. Sprich: Befinden sich bspw. 10 Units in einem Testheft und alle Units verwenden den selben Player, wird der Player nicht 10-mal eingerechnet, sondern nur einmal. Verwenden bswp. 5 der 10 Units einen anderen Player, wird die Größe der beiden Player mit eingerechnet.

**Testtaker:**

Die angezeigte Größe ist die Dateigröße der Testtaker-XML.

::: {.callout-tip}
Die Abhängigkeiten zur Größenberechnung können auch mit Hilfe der Browser Entwicklerkonsole detailliert betrachtet werden. Beim Wechsel zur Dateiansicht eines Arbeitsbereichs wird ein HTTP-POST abgesetzt. In der Antwort vom Server ist ein JSON-Objekt zu finden. Dieses listet alle Abhängigkeiten auf.
:::

### Wie starte ich einen Test und gibt es eine Art Voransicht?

Die Zugangsdaten der Testpersonen werden in der Testtaker-XML festgelegt. Diese XML muss mit allen anderen Testdateien in das Testcenter geladen werden. Nach Abmeldung kann sich dann eine Testperson mit den festgelegten Zugangsdaten und dem Schalter: "Weiter" anmelden. In der Testtaker-XML wird außer den Zugangsdaten noch der Modus der Testdurchführung festgelegt. Mithilfe dieses Modus kann festgelegt werden, ob der Test "heiß" ablaufen soll (run-hot-restart und run-hot-return) oder in einer Art Vorschau (run-review).

### Warum ist nach erfolgreicher Anmeldung kein Startbild mit den Testheften zu sehen?

Der Startbildschirm mit der Testheftauswahl ist nur zu sehen, wenn mehrere Testhefte in der Testtaker-XML angelegt sind. Gibt es mehrere Testhefte und werden diese nicht zur Auswahl angeboten: Eventuell besteht keine Internetverbindung. Es sollten entsprechende Routinen zur Fehlerbehebung beginnen (lose Kabel etc.).

### Warum wird für die Anmeldung kein Testheft gefunden?

Zugangsdaten prüfen. In der Testtaker-XML prüfen, ob dem Zugang ein entsprechendes Testheft zugewiesen ist und ob dieses Testheft im Arbeitsreich existiert.

### Warum ist der Schalter Testheft inaktiv?

Dies kann daraufhin deuten, dass das Testheft gesperrt ist. Je nach Konfiguration in der Booklet-XML kann es sein, dass die Testhefte nach Beendigung der Testung gesperrt werden. Ein Testheft kann eventuell auch über einen eingesetzen Gruppenmonitor von der Testleitung gesperrt wurden sein. In diesem Fall kann die Sperrung mit dem Gruppenmonitor auch wieder aufgehoben werden.

### Das Booklet kann bei einer Testdurchführung nicht geöffnet werden, es erscheint die folgende Meldung: *root element to Booklet should be: booklet*

Eventuell ist die verwendete Booklet-XML beschädigt oder beinhaltet ein sogenanntes BOM (byte order mark). Dieses BOM kann weitere Metadaten zu der Datei enthalten. Ist ein solches BOM in der Booklet-XML angelegt, erscheint diese Fehlermeldung im Testcenter, da das BOM nicht gelesen werden kann. Außerdem kann die Datei beschädigt sein, weil sie bspw. mit Word oder einem anderen nicht geeigneten Instrument verändert wurde. Verwenden Sie für die Bearbeitung der XML-Datei nur geeignete Editoren wie bspw. Notepad++. Arbeiten Sie bereits mit einem geeigneten Editor, achten Sie auf die Einstellungen zur Zeichenkodierung. Hier darf die Option: UTF-8-BOM nicht aktiv sein.

### Kann ich den Test überwachen oder steuern?

Das Testcenter stellt hierfür den **Gruppenmonitor** zur Verfügung. **Mehr dazu kann den Kapiteln: Testcenter/Gruppenmonitor entnommen werden.**

### Warum werden Aufgabeninhalte nicht präsentiert?

Werden die Inhalte erst während der Durchführung geladen (Konfiguration zum Ladenverhalten sind in der Booklet-XML festzulegen. Hier gibt es zwei Arten: LAZY und EAGER) kann es ein, dass Inhalte (Videos, Audios) noch geladen werden und die Testperson nicht sofort etwas sieht. Eventuell kann hier auch das Neuladen einer Seite hilfreich sein. Falls ein Gruppenmonitor zum Einsatz kommt, könnte dieser verwendet werden, um die Testperson noch einmal an den Anfang eines Block zu leiten und somit das Neuladen einer Aufgabe zu erzwingen.

### Warum werden GeoGebra-Elemente nicht angezeigt?

Eventuell wurde das für GeoGebra benötigte Paket noch nicht in den Arbeitsbereich der durchzuführenden Studie geladen. Mehr dazu finden Sie im Kapitel: Testcenter/Daten und Prozesse.

### Warum stimmt die Reihenfolge meiner Aufgabe nicht?

Die Reihenfolge der Aufgaben wird in der Booklet-XML festgelegt. Die Wiedergabe entspricht der hier angelegten Aufgaben von oben nach unten.

### Audios können nicht gestartet werden. Der Play-Knopf ist inaktiv.

Das Audio darf nicht Mono sein, sollte eine feste Bitrate aufweisen und muss im MP3-Format vorliegen.

### Warum werden Aufgabeninhalte in Chrome nur kurz angezeigt?

Bitte prüfen Sie, ob für Chrome eine Erweiterung mit dem Namen "Urban VPN proxy Unblocker" installiert ist. Falls ja, deinstallieren Sie diese Erweiterung probeweise.

### Wie kann ich den Test auswerten? Wo finde ich die Daten?

Das Testcenter speichert in bestimmten **Testmodi** die Ergebnisse eines Tests in dem Arbeitsbereich ab, in welchem sich auch die Testdateien für den Test befinden. Öffnen Sie den jeweiligen Arbeitsbereich und klicken Sie auf den Reiter: **Ergebnisse/Antworten**. Dort können Sie die Ergebnisse herunterladen. Die Dateien werden dann in einem CSV-Format gespeichert.



