---
lang: de
title: "Audio-Parameter"
---

Um auch bei schlechter Internetanbindung eine Studie durchführen zu können, sollten die Testheftgrößen so klein wie möglich gehalten werden. Die Testheftgröße hängt maßgeblich vom Einsatz audiovisueller Medien ab. Wenn nicht zwingend und auch mit anderen Aufgabenelementen darstellbar, sollten audiovisuelle Medien nur wenig eingesetzt werden. Da wo sie zum Einsatz kommen, muss auf die richtige Komprimierung geachtet werden. Hier muss immer ein Kompromiss zwischen Dateigröße und Qualität gefunden werden. Die nachfolgenden Einstellungen hat das IQB im Praxisalltag ermittelt. Sowohl Audio als auch Video sind so hoch wie möglich komprimiert bei ausreichender Wiedergabequalität. Es wird empfohlen diese Einstellungen für eigene Aufgabenformate so übernehmen. Nicht nur weil hier das Verhältnis Komprimierung und Qualität ausgewogen ist, sondern auch weil mit diesen Einstellungen eine gesicherte Wiedergabe durch den Player gewährleistet ist.

## Empfohlene Audioeinstellungen

Die nachfolgend genannten Audio-Einstellungen wurden mit dem Programm Audacity vorgenommen. Dieses wird am IQB hauptsächlich verwendet. Wenn andere Programme zum Einsatz kommen sollen, können sicherlich auch "modernere" Ausgabeformate, wie bspw. ACC erzeugt werden. Allerdings muss hier immer ein guter Weg zwischen Qualität und Größe gefunden werden. Bei der Wandlung in ACC können einzelne Programme bspw. eine Mindestbitbreite vorgeben, die wiederum zu größeren Dateien führt. Oder es kann keine feste Bitrate gewählt werden, sondern nur eine variable Bitrate. Variable Bitraten können aber zu Probleme bei der Wiedergabe im Testcenter führen. Das IQB würde aus diesen Gründen dazu raten, die unten genannten Einstellungen zu wählen, auch wenn diese nicht mehr ganz dem Stand der Technik entsprechen.

### Audios mit geringem Anspruch an die Qualität (nur Sprache):

* Kompression: MP3
* Kanal: Joint Stereo
* Abtastrate: 24000 Hz
* Bitraten Modus: Konstant
* Bitrate: 64kbps 

### Audios mit höherem Anspruch an die Qualität (Musik enthalten):

* Kompression: MP3
* Kanal: Joint Stereo
* Abtastrate: 44100 Hz
* Bitraten Modus: Konstant
* Bitrate: 96kbps 