---
lang: de
title: Arbeitsbereiche
---

# Grundfunktionen

Zur Organisation von Tests, Befragungen und System-Checks stehen Arbeitsbereiche zur Verfügung. Systemadministrator\*innen legen diese an und vergeben entsprechende Zugriffsberechtigungen. Mehr zum Thema Zugriffsrechte ist [hier](/Testcenter/Zugriffsrechte/index.qmd) zu finden. Die Benennung dieser Bereiche richtet sich günstigerweise nach dem Zweck der Studie.

Nach der Anmeldung präsentiert das System eine Liste aller Arbeitsbereiche, die für die Anmeldung freigegeben sind. Mit einem Klick auf den jeweiligen Arbeitsbereich wird dieser geöffnet. Zur Liste der Arbeitsbereiche kehrt man zurück, indem man auf das IQB-Logo (links oben) klickt.

Der Arbeitsbereich bietet drei Grundfunktionen. Diese können mit einem Klick auf den entsprechenden Reiter ausgewählt werden:

### Dateien

Hier können alle zu einem Test benötigten Dateien hochgeladen werden. Durch einen Klick auf eine bereits im System befindliche Datei, kann diese auch heruntergeladen werden. Die Dateien können einzeln oder verpackt in einem ZIP-Archiv geladen werden. Das Testcenter ordnet die geladenen Dateien anschließend bestimmten Gruppen zu. Diese sind:

* **Ressourcen:** <br>
Wie der Name schon sagt, werden hier Dateien gruppiert, die als Ressource zu einer Unit dienen. Das sind Unit-VOUD, Player-HTML, Unit-VOCS (Kodierung) und GeoGebra-Pakete (.itcr). 

* **Units:**<br>
Alle Dateien zur Unit-Definition (Unit-XML's).

* **Testhefte:**<br>
Alle Dateien zur Testheft-Definition (Booklet-XML's).

* **Teilnehmerlisten:**<br>
Alle Dateien mit den Zugangsdaten für die Testpersonen (Testtaker-XML's).

Sollen Dateien einzeln geladen werden, ist die Reihenfolge beim Laden entscheidend. Hintergrund: Die Dateien weisen untereinander Abhängigkeit auf. So sind bspw. in einem Testheft mehrere Units eingebunden. Diese Abhängigkeiten werden vom Testcenter geprüft. Soll bspw. ein Testheft geladen werden, bevor die dort deklarierten Units geladen wurden, wird eine Fehlermeldung generiert. Die folgende Reihenfolge muss eingehalten werden:

1. Ressourcendateien
2. Unit-XMLs
3. Booklet-XMLs
4. Testtaker-XMLs

::: {.callout-note}
Das löschen von Dateien, muss in umgekehrter Reihenfolge erfolgen.
:::

### System-Check-Berichte

Wurde ein System-Check durchgeführt, können hier die erzeugten System-Check-Berichte heruntergeladen werden.

### Ergebnisse/Antworten

Wurde eine Studie in einem Hot-Modus durchgeführt, können hier Antworten und Logs heruntergeladen werden. Wurde eine Studie in einem Review-Modus durchgeführt, können an dieser Stelle Kommentare heruntergeladen werden. 

::: {.callout-note}
Werden die Antwortdaten gelöscht, wird der Studienstand in den ursprünglichen Zustand versetzt. Die Studie kann dann ein weiteres Mal zustandsbereinigt durchgeführt werden.
:::




