---
lang: de
title: "IQB-Webanwendungen installieren"
format:
  html:
    toc: false
other-links:
  - text: IQB auf GitHub
    icon: github
    href: https://github.com/iqb-berlin
---

Sämtliche Programmierungen des IQB sind Open Source und öffentlich online verfügbar. Es ist nicht nötig, das IQB zu kontaktieren, sondern man folgt den Anleitungen.

Alle Webanwendungen des IQB sind serverbasiert, da sie online genutzt werden sollen. Man benötigt also einen Server und Basiskenntnisse dazu.

Allgemeine Hinweise:

* Die Installationen basieren auf der Virtualisierungslösung Docker. Es muss daher kein Unix-System sein, da Docker auch auf Windows verfügbar ist.
* Die Installation legt alle erforderlichen Komponenten an. Man muss also keine Datenbank vorher anlegen o. ä..
* Die Passung zum verwendeten Serversystem ist nicht immer perfekt, weil die Vielfalt der Systeme enorm ist. Die meisten Parameter der Konfiguration sind flexibel in Umgebungsvariablen gespeichert.
* Sowohl die Installation als auch später das Update sind scriptgesteuert. Man ruft also eine Installationsroutine auf und beantwortet die wichtigsten Fragen.

```{mermaid}
flowchart LR
    A(Aufgabenentwicklung<br/><b>IQB-Studio</b>)
    B(Testdurchführung<br/><b>IQB-Testcenter</b>)
    C(Kodierung<br/><b>IQB-Kodierbox</b>)
    style A fill:#adf, stroke:#037
    style B fill:#adf, stroke:#037
    style C fill:#adf, stroke:#037
    A --> B
    B --> C
```

# Weiterlesen

## IQB-Studio

* Installationsanleitung auf [GitHub](https://github.com/iqb-berlin/studio-lite#readme-ov-file)
* Portalbeschreibung des [Super-Admin-Accounts](studio-super-admin/index.qmd)

## IQB-Testcenter

* Installationsanleitung auf [GitHub](https://github.com/iqb-berlin/testcenter#readme-ov-file)
* Hinweise zur [Konfiguration](configuration.qmd) bei/nach der Installation
* Durchführung als [Offline-Szenario](offline.qmd)
* Strategien zum [Lasttest](load-test.qmd)
* [Release-Plan](releases.qmd)
* Diskussion zur [Datensicherheit](security.qmd)
* Zu automatischen [Software-Tests](e2e.qmd)

## IQB-Kodierbox

Die Webanwendung IQB-Kodierbox befindet sich in Entwicklung. Sobald die Erprobungen weiter fortgeschritten sind, finden Sie an dieser Stelle weitere Informationen.