---
lang: de
title: "Testinhalte"
---

# Begriff "Testinhalte"

Ein Test im Kontext des IQB-Testcenters ist die Gesamtheit aller ihrer Testinhalte, also eine konfigurierbare, strukturierte Sammlung von Aufgaben oder Fragen, die einer Testperson in einer bestimmten Reihenfolge präsentiert werden, um spezifische Informationen oder Leistungen zu erheben.

Unter Testinhalte werden alle Dateien verstanden, die im Vorfeld eines Tests oder einer Befragung hochgeladen werden müssen. Sie bestimmen die Testitems, den Testablauf und die Personen, die diese Tests durchführen dürfen. Das Testcenter greift nie auf Inhalts-Ressourcen außerhalb der jeweiligen Testcenter-Installation zu.

Es sind für die Testvorbereitung mindestens 4 Arten von Datendateien erforderlich. Die folgende Darstellung zeigt auch die Abhängigkeit der Inhaltsdateien voneinander. Da das Testcenter diese Abhängigkeiten auf Gültigkeit prüft, müssen die Inhaltsdateien in der dargestellten Reihenfolge in das Testcenter hochgeladen werden (**von links nach rechts**). Sie können auch nur in der entgegengesetzten Reihenfolge gelöscht werden, um keine Inkonsistenzen zu erzeugen.

::: {#fig-dep}
```{mermaid}
flowchart LR
  A[Basis-Pakete für Player] --> B[Player]
  B --> C[Units]
  C --> D[Booklets]
  D --> E[Testtakers]
```
Player sind abhängig von Basis-Pakete für Player, Units sind abhängig von Player etc.
:::

## Basis-Pakete für Player

Die Verona-Architektur sieht vor, dass ein Player während der Laufzeit Code nachladen darf. Es handelt sich also nicht um Testinhalte, die zu Beginn geladen werden, sondern nach Bedarf. Dieses Vorgehen ist erforderlich z. B. im Zusammenhang mit GeoGebra: Erst wenn die Testperson an eine Stelle kommt innerhalb der Unit, wo eine GeoGebra-Darstellung nötig ist, lädt der Player das Paket. Ob ein Player, der in der Studie verwendet wird, eine solche Abhängigkeit hat, muss der Player-Dokumentation entnommen werden. Ein Basis-Paket ist eine ZIP-Datei und muss die Dateiendung **.itcr.zip** haben.

Das GeoGebra-Paket kann [hier](https://download.geogebra.org/package/geogebra-math-apps-bundle) heruntergeladen werden. Die heruntergeladene Datei muss dann in `GeoGebra.itcr.zip` umbenannt werden und in den Arbeitsbereich geladen werden, in dem sich auch der Player befindet, der GeoGebra als Bedingung enthält. GeoGebra wird aus lizenzrechtlichen Gründen nicht mit dem IQB-Testcenter ausgeliefert.

## Player

Nicht das Testcenter stellt die Testaufgaben bzw. die Frageitems dar, sondern eine separate Programmierung "Player" ist dafür verantwortlich. Das Testcenter stellt lediglich den umgebenden Bildschirmbereich bereit und sorgt für das Speichern der Antworten. Dadurch kann flexibel die Art der Darstellung geändert werden, indem pro Test ein anderer Player eingesetzt wird. Es kann damit eine neue, nur für einen Test bestimmte Darstellung erreicht werden, ohne die Darstellung anderer Tests zu stören.

Für eine Testdurchführung ist mindestens ein Player notwendig. Es kann vorkommen, dass ein Player ein oder mehrere [Basis-Pakete](#basis-pakete-für-player) benötigt. Ein Player ist eine Html-Datei und folgt der Verona-Spezifikation. Die bereitgestellten Player des IQB [finden Sie unten](#units-des-iqb).

## Units

Eine Unit entspricht einer Seite, meist mit Frageitems, im Testauflauf. Es kann sich auch um eine simple Begrüßungsseite handeln völlig ohne Items. Wie genau Items zu Units gebündelt werden, hängt von vielen Faktoren ab und ändert sich vielleicht auch mal. Aus der Sicht des Testcenters ist ein Test eine Folge von Units, und welche Funktion die Unit konkret hat, ist unerheblich. Units sollen unabhängig gedacht werden - unabhängig voneinander und von konkreten Tests. Die Platzierung einer Unit in einem spezifischen Test an einer bestimmten Position soll dessen Entwicklung nicht beeinflussen.

Es ist mindestens eine XML-Datei pro Unit erforderlich. Bei großen oder komplexen Units sind Teile der Unit-Daten ausgelagert in separate Dateien, z. B. im JSON-Format. Die XML-Datei ist strikt spezifiziert und enthält z. B. eine ID. Außerdem muss ein Verweis auf einen Player enthalten sein.

Weiter: [Unit-XML im Detail](unit-xml.qmd)

## Booklets

Ein Booklet definiert die Abfolge von Units für einen bestimmten Test, die eine Testperson nacheinander angezeigt bekommt und bearbeiten soll. Es gibt eine Vielzahl von Parametern zur Steuerung.

::: {.callout-note}
Ab Ende 2024 wird es möglich sein, konditionale Unit-Blöcke zu definieren. Die Entscheidung, welche Units der Testperson vorgelegt werden, ergibt sich dann aus den Antworten vorangegangener Units.
:::

Eine Booklet-Datei ist stets eine strikt spezifizierte XML-Datei. Für einen Test muss mindestens ein Booklet definiert werden. Die Units sind im Booklet über ihre ID referenziert und müssen ebenfalls im Arbeitsbereich vorhanden sein.

Weiter: [Booklet-XML im Detail](booklet-xml.qmd)

## Testtakers

Eine Testtaker-Datei ist ebenfalls eine strikt spezifizierte XML-Datei. Es werden Login-Daten definiert und die jeweils zu nutzenden Booklets über ihre ID aufgeführt. Es muss mindestens eine Testtaker-Datei im Arbeitsbereich hochgeladen werden, um einen Test zu ermöglichen.

Für die Gestaltung eines Logins gibt es mehrere Varianten, um eine gute Passung zur Testpopulation und zur Durchführungspraxis zu erreichen. Z. B. kann auf das Kennwort verzichtet werden, um mit einem Link sofort die Authentifikation zu erreichen.

Neben der "heißen" Durchführung eines Tests bzw. einer Befragung, kann anhand weiterer "Modus"-Parameter gesteuert werden, dass keine Antworten gespeichert werden (z. B. für die Demonstration von Units) oder dass Kommentare vergeben werden können (für das Review von Booklets bzw. Units).

Weiter: [Testtaker-XML im Detail](testtaker-xml.qmd)

