---
lang: de
title: "Organisieren"
---

Die Texte dieses Abschnittes fokussieren auf die Rolle der **Leitung eines Entwicklungsteams**. Mit besonderen Rechten können Einstellungen im IQB-Studio vorgenommen werden, mit denen die Entwicklung auch großer Aufgabenmengen effizient erfolgen kann.

Lesen Sie im Detail:

* [Rollen und Rechte](roles.qmd): Die Beteiligten nehmen unterschiedliche Funktionen wahr und es ist wichtig, ihnen entsprechende Rechte für die Ansicht oder das Ändern zu geben. Der Text stellt die Möglichkeiten dar, über Zugriffsrechte die Arbeit zu organisieren.
* [Arbeitsbereiche](workspaces.qmd): Große Mengen an Aufgaben müssen gruppiert werden. Im IQB-Studio stehen dafür die Ebenen Bereichsgruppe, Arbeitsbereich und Aufgabengruppe zur Verfügung.
* [Verschieben und Kopieren](move-and-copy.qmd): Effizientes Arbeiten über Arbeitsbereiche hinweg.
* [Aufgabenfolgen](task-sequence.qmd): Schnelle Zusammenstellung von Aufgaben zum Review mit zusätzlichen Daten wie Kommentare und Kodierschema.
* [Verona-Module](verona-modules.qmd): Zuweisung von Verona-Modulen für Player, Editor und Schemer
* [Metadaten](metadata.qmd) von Aufgaben und Items: Profile für Metadaten zuweisen
